/*
    날짜 : 25/07/18
    이름 : 고정현
    내용 : 연습문제1
*/    
실습 1-1
ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE user shop identified by 1111;
grant connect, resource, unlimited tablespace TO shop;

실습 1-2
DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER (
    CID VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    HP  CHAR(13) UNIQUE,
    ADDRESS VARCHAR2(200),
    RDATE   DATE NOT NULL
);

CREATE TABLE PRODUCT (
    PNO      NUMBER(4) PRIMARY KEY,
    PNAME    VARCHAR2(30) NOT NULL,
    STOCK    NUMBER DEFAULT 0,
    PRICE    NUMBER, 
    COMPANY  VARCHAR2(20)
);

CREATE TABLE ORDERS (
    ORD_NO      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ORD_CID     VARCHAR2(20),
    ORD_PNO     NUMBER(4),
    ORD_CNT     NUMBER DEFAULT 1,
    ORD_DATE    DATE NOT NULL
); 

실습 1-3
insert into customer values 
('c101', '김유신','010-1234-1001', '김해시 봉황동', TO_DATE('2022-01-01', 'YYYY-MM-DD'));
insert into customer values 
('c102', '김춘추','010-1234-1002', '경주시 보문동', TO_DATE('2022-01-02', 'YYYY-MM-DD'));
insert into customer values 
('c103', '장보고','010-1234-1003', '완도군 청산면', TO_DATE('2022-01-03', 'YYYY-MM-DD'));
insert into customer values 
('c104', '강감찬','010-1234-1004', '서울시 마포구', TO_DATE('2022-01-04', 'YYYY-MM-DD'));
insert into customer values 
('c105', '이성계',NULL, NULL, TO_DATE('2022-01-05', 'YYYY-MM-DD'));
insert into customer values 
('c106', '정철','010-1234-1006','경기도 용인시', TO_DATE('2022-01-06', 'YYYY-MM-DD'));
insert into customer values 
('c107', '허준',NULL,NULL, TO_DATE('2022-01-07', 'YYYY-MM-DD'));
insert into customer values 
('c108', '이순신' ,'010-1234-1008', '서울시 영등포구' , TO_DATE('2022-01-08', 'YYYY-MM-DD'));
insert into customer values 
('c109', '송상현','010-1234-1009', '부산시 동래구', TO_DATE('2022-01-09', 'YYYY-MM-DD'));
insert into customer values 
('c110', '정약용','010-1234-1010', '경기도 광주시', TO_DATE('2022-01-10', 'YYYY-MM-DD'));


insert into product values
(1,'새우깡',5000,1500,'농심');
insert into product values
(2,'초코파이',2500,2500,'오리온');
insert into product values
(3,'포카칩',3600,1700,'오리온');
insert into product values
(4,'양파링',1250,1800,'농심');
insert into product values
(5,'죠리퐁',2200,NULL,'크라운');
insert into product values
(6,'마가렛트',3500,3500,'롯데');
insert into product values
(7,'뿌셔뿌셔',1650,1200,'오뚜기');

insert into ORDERS values
(1,'c102',3,2,TO_DATE('2022-07-01 13:15:10','YYYY-MM-DD HH24:MI:SS'));
insert into ORDERS values
(2,'c101',4,1,TO_DATE('2022-07-01 14:16:11','YYYY-MM-DD HH24:MI:SS'));
insert into ORDERS values
(3,'c108',1,1,TO_DATE('2022-07-01 17:23:18','YYYY-MM-DD HH24:MI:SS'));
insert into ORDERS values
(4,'c109',6,5,TO_DATE('2022-07-02 10:46:36','YYYY-MM-DD HH24:MI:SS'));
insert into ORDERS values
(5,'c102',2,1,TO_DATE('2022-07-03 09:15:37','YYYY-MM-DD HH24:MI:SS'));
insert into ORDERS values
(6,'c101',7,3,TO_DATE('2022-07-03 12:35:12','YYYY-MM-DD HH24:MI:SS'));
insert into ORDERS values
(7,'c110',1,2,TO_DATE('2022-07-03 16:55:36','YYYY-MM-DD HH24:MI:SS'));
insert into ORDERS values
(8,'c104',2,4,TO_DATE('2022-07-04 14:23:23','YYYY-MM-DD HH24:MI:SS'));
insert into ORDERS values
(9,'c102',1,3,TO_DATE('2022-07-04 21:54:34','YYYY-MM-DD HH24:MI:SS'));
insert into ORDERS values
(10,'c107',6,1,TO_DATE('2022-07-05 14:21:03','YYYY-MM-DD HH24:MI:SS'));

실습 1-4
SELECT * FROM CUSTOMER;
실습 1-5
SELECT CID,NAME,HP FROM CUSTOMER;
실습 1-6
SELECT * FROM PRODUCT;
실습 1-7
SELECT COMPANY FROM PRODUCT;
실습 1-8
SELECT DISTINCT COMPANY FROM PRODUCT;
실습 1-9
SELECT PNAME, PRICE FROM PRODUCT;
실습 1-10
SELECT PNAME, PRICE + 500 AS "조정단가" FROM PRODUCT;
실습 1-11
SELECT PNAME, STOCK, PRICE FROM PRODUCT WHERE COMPANY = '오리온';
실습 1-12
SELECT ORD_PNO, ORD_CNT, ORD_DATE FROM ORDERS WHERE ORD_CID = 'c102';
실습 1-13
SELECT ORD_PNO, ORD_CNT, ORD_DATE FROM ORDERS WHERE ORD_CNT >=2;
실습 1-14
SELECT * FROM PRODUCT WHERE PRICE BETWEEN 1000 AND 2000;
실습 1-15
SELECT CID, NAME, HP, ADDRESS FROM CUSTOMER WHERE NAME LIKE '김%';
실습 1-16
SELECT CID, NAME, HP, ADDRESS FROM CUSTOMER WHERE LENGTH(NAME) = 2;
실습 1-17
SELECT * FROM CUSTOMER WHERE HP IS NULL;
실습 1-18
SELECT * FROM CUSTOMER WHERE ADDRESS IS NOT NULL;
실습 1-19
SELECT * FROM CUSTOMER ORDER BY RDATE DESC;
실습 1-20
SELECT * FROM ODERS 
    WHERE ORD_CNT >= 3
    ORDER BY ORD_CNT DESC, ORD_PNO ASC;
실습 1-21
SELECT AVG(PRICE) FROM PRODUCT;
실습 1-22
SELECT SUM(STOCK) AS "재고량 합계" FROM PRODUCT WHERE COMPANY = '농심';
실습 1-23
SELECT COUNT(*) AS 고객수 FROM CUSTOMER;
실습 1-24
SELECT COUNT(DISTINCT COMPANY) AS "제조업체 수" FROM PRODUCT;
실습 1-25
SELECT 
    ORD_PNO AS "주문상품 번호" 
    SUM(ORD_CNT) AS "총 주문 수량"
FROM ORDERS;
GROUP BY ORD_PNO
ORDER BY ORD_PNO ASC;
실습 1-26
SELECT
    COMPANY
    COUNT(*) AS 제품수,
    MAX(PRICE) AS 최고가
FROM PRODUCT;
GROUP BY COMPANY
GROUP BY COMPANY;

실습 1-27
SELECT
    company as 제조업체,
    count(*) as 제품수,
    max(price) as 최고가
FROM PRODUCT
group by company
having count(*) >= 2;
실습 1-28
SELECT ORD_PNO, ORD_CID, SUM(ORD_CNT) AS "총 주문수량" FROM ORDERS
GROUP BY ORD_PNO, ORD_CID ORDER BY ORD_PNO;
실습 1-29

SELECT ORD_CID, PNAME FROM ORDERS A
JOIN PRODUCT B
ON A.ORD_PNO = B.PNO
WHERE ORD_CID = 'C102';
실습 1-30
SELECT ORD_CID, NAME, PNAME, ORD_DATE FROM ORDERS A
JOIN CUSTOMER B ON A.ORD_CID = B.CID
JOIN PRODUCT C ON A.ORD_PNO = C.PNO
WHERE ORD_DATE LIKE '2022-07-03%';


